name: JSON Validation CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ fix-json-validator ]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate JSON
        uses: walbo/validate-json@v1.1.0
        with:
          files: data/**.json
          schema: schema.json
          schema-version: draft-2020-12