name: JSON Validation CI

on:
  pull_request:
    branches: [ master ]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate other schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./schema.json
          json_path_pattern: \/data\/.*\.json$